services:
  sparki:
    container_name: sparki
    user: admin
    image: project:local
    build:
      context: ./
      dockerfile: Dockerfile
      target: development_only_stage
      args:
        # Images built with HAS_SUDO=1 will have sudo installed and a privileged
        # user created. The CICD will set this to 0 to reduce the attack surface
        # of the image, but during development, you may want to have sudo.
        HAS_SUDO: "${HAS_SUDO:-1}"
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    restart: unless-stopped
    ports:
      - 8001
    # You want the container to stay up forever while you're developing.
    command: sleep infinity
    volumes:
      - type: bind
        source: ./
        target: /opt/repo/
    environment:
      - USERID=${UID:-1000}
      - GROUPID=${GID:-1000}
    networks:
      - local-default

networks:
  local-default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1350
    ipam:
      config:
        - subnet: 192.168.4.0/24
