describe("SPARKI::subsetReports()", {
  test_that("subsetReports() does not fail when the species name is white space-delimited and so are the taxon names in the report", {
    logger::log_threshold(logger::OFF)

    # Get path to test directory
    path_to_std <- get_test_std_report_dir("valid")

    # Load the standard reports and define species names for the tests.
    std_reports <- SPARKI::load_STDreports(path_to_std)
    species_name <- "Homo sapiens" # Should not fail.

    # Check no error is raised.
    expect_no_error(SPARKI::subsetReports(std_reports, species_name))

    # Inspect the dataframe generated by SPARKI::subsetReports().
    out <- SPARKI::subsetReports(std_reports, species_name)
    expect_false(species_name %in% out[, SPARKI:::COLNAME_STD_TAXON])

  })

  test_that("subsetReports() does not fail when the species name is white space-delimited but the report has underscore-delimited taxon names", {
    logger::log_threshold(logger::OFF)

    # Get path to test directory
    path_to_std <- get_test_std_report_dir("valid")

    # Load the standard reports and define species names for the tests.
    std_reports <- SPARKI::load_STDreports(path_to_std)
    species_name <- "Homo sapiens" # Should not fail.

    # Deliberately replace white spaces with underscores in the standard reports and carry out
    # tests again.
    std_reports[[SPARKI:::COLNAME_STD_TAXON]] <- gsub(" ", "_", std_reports[[SPARKI:::COLNAME_STD_TAXON]])

    # Check no error is raised.
    expect_no_error(SPARKI::subsetReports(std_reports, species_name))

    # Inspect the dataframe generated by SPARKI::subsetReports().
    out <- SPARKI::subsetReports(std_reports, species_name)
    expect_false(species_name %in% out[, SPARKI:::COLNAME_STD_TAXON])
  })

  test_that("subsetReports() does not fail when the species name is underscore-delimited but the report has white space-delimited taxon names", {
    logger::log_threshold(logger::OFF)

    # Get path to test directory
    path_to_std <- get_test_std_report_dir("valid")

    # Load the standard reports and define species names for the tests.
    std_reports <- SPARKI::load_STDreports(path_to_std)
    species_name <- "Homo_sapiens" # Should not fail.

    # Check no error is raised.
    expect_no_error(SPARKI::subsetReports(std_reports, species_name))

    # Inspect the dataframe generated by SPARKI::subsetReports().
    out <- SPARKI::subsetReports(std_reports, species_name)
    expect_false(species_name %in% out[, SPARKI:::COLNAME_STD_TAXON])
  })

  test_that("subsetReports() does not fail when the species name is underscore-delimited and so are the taxon names in the report", {
    logger::log_threshold(logger::OFF)

    # Get path to test directory
    path_to_std <- get_test_std_report_dir("valid")

    # Load the standard reports and define species names for the tests.
    std_reports <- SPARKI::load_STDreports(path_to_std)
    species_name <- "Homo_sapiens" # Should not fail.

    # Deliberately replace white spaces with underscores in the standard reports.
    std_reports[[SPARKI:::COLNAME_STD_TAXON]] <- gsub(" ", "_", std_reports[[SPARKI:::COLNAME_STD_TAXON]])

    # Check no error is raised.
    expect_no_error(SPARKI::subsetReports(std_reports, species_name))

    # Inspect the dataframe generated by SPARKI::subsetReports().
    out <- SPARKI::subsetReports(std_reports, species_name)
    expect_false(species_name %in% out[, SPARKI:::COLNAME_STD_TAXON])
  })

  test_that("SPARKI::subsetReports() fails when the species name does not follow any of the expected formats", {
    logger::log_threshold(logger::OFF)

    # Get path to test directory
    path_to_std <- get_test_std_report_dir("valid")

    # Load the standard reports and define species names that should fail.
    std_reports <- SPARKI::load_STDreports(path_to_std)
    names_that_should_fail <- c("Homo+sapiens", "Homo/sapiens", "Homo.sapiens", "Homosapiens", "Homo  sapiens")

    # Carry out tests.
    for (species_name in names_that_should_fail) {
      expect_error(SPARKI::subsetReports(std_reports, species_name))
    }
  })
})

describe("check_species_in_report()", {
  test_that("check_species_in_report() behaves as expected when the species name is white space-delimited and so are the taxon names in the report", {
    logger::log_threshold(logger::OFF)

    # Get path to test directory
    path_to_std <- get_test_std_report_dir("valid")

    # Load the standard reports and define species names that should fail.
    std_reports <- SPARKI::load_STDreports(path_to_std)
    species_name <- "Homo sapiens" # Should not fail.

    actual_value <- SPARKI:::check_species_in_report(std_reports, species_name)
    expected_value <- "Homo sapiens"
    expect_equal(actual_value, expected_value)

    expect_no_error(SPARKI:::check_species_in_report(std_reports, species_name))
  })

  test_that("check_species_in_report() behaves as expected when the species name is white space-delimited but the taxon names in the report are underscore-delimited", {
    logger::log_threshold(logger::OFF)

    # Get path to test directory
    path_to_std <- get_test_std_report_dir("valid")

    # Load the standard reports and define species names that should fail.
    std_reports <- SPARKI::load_STDreports(path_to_std)
    species_name <- "Homo sapiens" # Should not fail.

    # Deliberately replace white spaces with underscores in the standard reports.
    std_reports[[SPARKI:::COLNAME_STD_TAXON]] <- gsub(" ", "_", std_reports[[SPARKI:::COLNAME_STD_TAXON]])

    actual_value <- SPARKI:::check_species_in_report(std_reports, species_name)
    expected_value <- "Homo_sapiens"
    expect_equal(actual_value, expected_value)

    expect_no_error(SPARKI:::check_species_in_report(std_reports, species_name))
  })

  test_that("check_species_in_report() behaves as expected when the species name is underscore-delimited but the taxon names in the report are white space-delimited", {
    logger::log_threshold(logger::OFF)

    # Get path to test directory
    path_to_std <- get_test_std_report_dir("valid")

    # Load the standard reports and define species names that should fail.
    std_reports <- SPARKI::load_STDreports(path_to_std)
    species_name <- "Homo_sapiens" # Should not fail.

    actual_value <- SPARKI:::check_species_in_report(std_reports, species_name)
    expected_value <- "Homo sapiens"
    expect_equal(actual_value, expected_value)

    expect_no_error(SPARKI:::check_species_in_report(std_reports, species_name))
  })

    test_that("check_species_in_report() behaves as expected when the species name is underscore-delimited and so are the taxon names in the report", {
    logger::log_threshold(logger::OFF)

    # Get path to test directory
    path_to_std <- get_test_std_report_dir("valid")

    # Load the standard reports and define species names that should fail.
    std_reports <- SPARKI::load_STDreports(path_to_std)
    species_name <- "Homo_sapiens" # Should not fail.

    # Deliberately replace white spaces with underscores in the standard reports.
    std_reports[[SPARKI:::COLNAME_STD_TAXON]] <- gsub(" ", "_", std_reports[[SPARKI:::COLNAME_STD_TAXON]])

    actual_value <- SPARKI:::check_species_in_report(std_reports, species_name)
    expected_value <- "Homo_sapiens"
    expect_equal(actual_value, expected_value)

    expect_no_error(SPARKI:::check_species_in_report(std_reports, species_name))
  })
})
