my_library <- "/lustre/scratch126/casm/team113da/users/jb62/projects/sparki/"
source(paste0(my_library, "src/main.R"))
source(paste0(my_library, "src/exceptions.R"))
source(paste0(my_library, "R/load-data.R"))
source(paste0(my_library, "R/plot-classification-summary.R"))
source(paste0(my_library, "R/plot-domain-reads.R"))
source(paste0(my_library, "R/plot-minimisers.R"))
source(paste0(my_library, "R/plot-significance.R"))
source(paste0(my_library, "R/reports-add-info.R"))
source(paste0(my_library, "R/reports-assess-statistics.R"))
source(paste0(my_library, "R/reports-merge.R"))
source(paste0(my_library, "R/reports-subset.R"))
source(paste0(my_library, "R/constants.R"))

###################
# Parse arguments #
###################

option_list <- list(
    optparse::make_option(
        c("--std-reports"),
        dest = "std_reports",
        action = "store",
        default = NA,
        type = "character",
        help = "Path to directory containing standard reports generated by Kraken2."
    ),
    optparse::make_option(
        c("--mpa-reports"),
        dest = "mpa_reports",
        action = "store",
        default = NA,
        type = "character",
        help = "Path to directory containing standard reports generated by Kraken2."
    ),
    optparse::make_option(
        c("--organism"),
        dest = "organism",
        action = "store",
        default = "Homo sapiens",
        type = "character",
        help = "Species of the organism being analysed."
    ),
    optparse::make_option(
        c("-r", "--reference"),
        dest = "refdb",
        action = "store",
        default = NA,
        type = "character",
        help = "Path to Kraken2 reference database."
    ),
    optparse::make_option(
        c("-m", "--metadata"),
        dest = "metadata",
        action = "store",
        default = NA,
        type = "character",
        help = "Path to metadata file [optional]."
    ),
    optparse::make_option(
        c("--sample-col"),
        dest = "sample_col",
        action = "store",
        default = NA,
        type = "character",
        help = "Sample column in metadata table [if metadata file was provided]."
    ),
    optparse::make_option(
        c("-c", "--columns"),
        dest = "columns",
        action = "store",
        default = NA,
        type = "character",
        help = "Comma-separated column names [if metadata file was provided]."
    ),
    optparse::make_option(
        c("-p", "--prefix"),
        dest = "prefix",
        action = "store",
        default = NA,
        type = "character",
        help = "Prefix of output files."
    ), 
    optparse::make_option(
        c("-o", "--outdir"),
        dest = "outdir",
        action = "store",
        default = NA,
        type = "character",
        help = "Path to output directory."
    ),
    optparse::make_option(
        c("-v", "--verbose"),
        dest = "verbose",
        action = "store_true",
        default = FALSE,
        type = "logical",
        help = "Verbosity level."
    ),
    optparse::make_option(
        c("--include-eukaryotes"),
        dest = "inc_eukaryotes",
        action = "store_true",
        default = FALSE,
        type = "logical",
        help = "Include eukaryotes in the final results table and plots."
    ),
    optparse::make_option(
        c("--include-sample-names"),
        dest = "inc_sample_names",
        action = "store_true",
        default = FALSE,
        type = "logical",
        help = "Include sample names in the plots."
    ),
    optparse::make_option(
        c("-d", "--domain"),
        dest = "domain",
        action = "store",
        default = NA,
        type = "character",
        help = "Comma-separated list with domains of interest (e.g. Viruses,Bacteria)."
    ),
    optparse::make_option(
        c("-s", "--samples-to-remove"),
        dest = "remove",
        action = "store",
        default = NA,
        type = "character",
        help = "Samples to remove from SPARKI analysis."
    )
)

# Parse the arguments.
parser <- optparse::OptionParser(
    option_list = option_list,
    add_help_option = TRUE
)
arguments <- optparse::parse_args(parser)

# Compute PCA.
process_kraken2(
        std_reports_path = arguments$std_reports, 
        mpa_reports_path = arguments$mpa_reports,
        organism = arguments$organism,
        reference_path = arguments$refdb, 
        metadata_path = arguments$metadata,
        metadata_sample_col = arguments$sample_col,
        metadata_columns = arguments$columns,
        outdir_path = arguments$outdir,
        prefix = arguments$prefix,
        verbose = arguments$verbose,
        include_eukaryotes = arguments$inc_eukaryotes,
        include_sample_names = arguments$inc_sample_names,
        domain = arguments$domain,
        remove = arguments$remove
    )

