#' Command Line Interface for SPARKI
#'
#' @return NULL
#' @export
cli <- function() {
  # Define the options for the command line interface.
  option_list <- list(
    optparse::make_option(
      c("--std-reports"),
      dest = "std_reports",
      action = "store",
      default = NA,
      type = "character",
      help = "Path to directory containing standard reports generated by Kraken2."
    ),
    optparse::make_option(
      c("--mpa-reports"),
      dest = "mpa_reports",
      action = "store",
      default = NA,
      type = "character",
      help = "Path to directory containing standard reports generated by Kraken2."
    ),
    optparse::make_option(
      c("--organism"),
      dest = "organism",
      action = "store",
      default = "Homo sapiens",
      type = "character",
      help = "Species of the organism being analysed."
    ),
    optparse::make_option(
      c("-r", "--reference"),
      dest = "refdb",
      action = "store",
      default = NA,
      type = "character",
      help = "Path to Kraken2 reference database."
    ),
    optparse::make_option(
      c("-m", "--metadata"),
      dest = "metadata",
      action = "store",
      default = NA,
      type = "character",
      help = "Path to metadata file [optional]."
    ),
    optparse::make_option(
      c("--sample-col"),
      dest = "sample_col",
      action = "store",
      default = NA,
      type = "character",
      help = "Sample column in metadata table [if metadata file was provided]."
    ),
    optparse::make_option(
      c("-c", "--columns"),
      dest = "columns",
      action = "store",
      default = NA,
      type = "character",
      help = "Comma-separated column names [if metadata file was provided]."
    ),
    optparse::make_option(
      c("-p", "--prefix"),
      dest = "prefix",
      action = "store",
      default = "",
      type = "character",
      help = "Prefix of output files."
    ),
    optparse::make_option(
      c("-o", "--outdir"),
      dest = "outdir",
      action = "store",
      default = NA,
      type = "character",
      help = "Path to output directory."
    ),
    optparse::make_option(
      c("-v", "--verbose"),
      dest = "verbose",
      action = "store_true",
      default = FALSE,
      type = "logical",
      help = "Verbosity level."
    ),
    optparse::make_option(
      c("--include-eukaryotes"),
      dest = "inc_eukaryotes",
      action = "store_true",
      default = FALSE,
      type = "logical",
      help = "Include eukaryotes in the final results table and plots."
    ),
    optparse::make_option(
      c("--include-sample-names"),
      dest = "inc_sample_names",
      action = "store_true",
      default = FALSE,
      type = "logical",
      help = "Include sample names in the plots."
    ),
    optparse::make_option(
      c("-d", "--domain"),
      dest = "domain",
      action = "store",
      default = NA,
      type = "character",
      help = "Comma-separated list with domains of interest (e.g. Viruses,Bacteria)."
    ),
    optparse::make_option(
      c("-s", "--samples-to-remove"),
      dest = "remove",
      action = "store",
      default = NA,
      type = "character",
      help = "Samples to remove from SPARKI analysis."
    ),
    optparse::make_option(
      c("--version"),
      action = "store_true",
      default = FALSE,
      type = "logical",
      help = "Print version information and exit."
    )
  )

  # Collect the command line arguments
  from_cli_args <- commandArgs(trailingOnly = TRUE)

  # Create the parser
  parser <- optparse::OptionParser(
    option_list = option_list,
    add_help_option = TRUE,
    description = CLI_DESCRIPTION,
    prog = CLI_PROGRAM_NAME
  )

  # Parse the CLI arguments into R objects
  arguments <- optparse::parse_args(parser, args = from_cli_args)

  # Check for version flag first
  if (arguments$version) {
    version <- utils::packageVersion("SPARKI")
    cat(sprintf("%s version %s\n", CLI_PROGRAM_NAME, version))
    return(invisible())
  }

  #  Check all required arguments have been provided.
  required_arguments <- c(
    arguments$std_reports, arguments$mpa_reports, arguments$organism,
    arguments$refdb, arguments$outdir, arguments$domain
  )
  for (argument in required_arguments) {
    if (is.na(argument)) stop(CLI_ERROR_ARGUMENT_NOT_PROVIDED, argument)
  }

  # If verbose, print all arguments to be used.
  if (arguments$verbose) {
    message(CLI_INFO_ARGUMENTS)
    message(CLI_INFO_ARGUMENT_STD_REPORTS, arguments$std_reports)
    message(CLI_INFO_ARGUMENT_MPA_REPORTS, arguments$mpa_reports)
    message(CLI_INFO_ARGUMENT_ORGANISM, arguments$organism)
    message(CLI_INFO_ARGUMENT_REFERENCE, arguments$refdb)
    message(CLI_INFO_ARGUMENT_METADATA, arguments$metadata)
    message(CLI_INFO_ARGUMENT_SAMPLE_COL, arguments$sample_col)
    message(CLI_INFO_ARGUMENT_COLUMNS, arguments$columns)
    message(CLI_INFO_ARGUMENT_OUTDIR, arguments$outdir)
    message(CLI_INFO_ARGUMENT_PREFIX, arguments$prefix)
    message(CLI_INFO_ARGUMENT_VERBOSE, arguments$verbose)
    message(CLI_INFO_ARGUMENT_INC_EUKARYOTES, arguments$inc_eukaryotes)
    message(CLI_INFO_ARGUMENT_INC_SAMPLE_NAMES, arguments$inc_sample_names)
    message(CLI_INFO_ARGUMENT_DOMAIN, arguments$domain)
    message(CLI_INFO_ARGUMENT_SAMPLES_TO_REMOVE, arguments$remove)
  }

  # Carry out SPARKI analysis.
  run_sparki(
    std_reports_path = arguments$std_reports,
    mpa_reports_path = arguments$mpa_reports,
    organism = arguments$organism,
    reference_path = arguments$refdb,
    metadata_path = arguments$metadata,
    metadata_sample_col = arguments$sample_col,
    metadata_columns = arguments$columns,
    outdir_path = arguments$outdir,
    prefix = arguments$prefix,
    verbose = arguments$verbose,
    include_eukaryotes = arguments$inc_eukaryotes,
    include_sample_names = arguments$inc_sample_names,
    domain = arguments$domain,
    remove = arguments$remove
  )
}
