#' Command Line Interface for SPARKI
#'
#' @return NULL
#' @export
cli <- function() {
  # Define the options for the command line interface.
  option_list <- list(
    optparse::make_option(
      c("--std-reports"),
      dest = "std_reports",
      action = "store",
      default = NA,
      type = "character",
      help = "Path to directory containing standard reports generated by Kraken2."
    ),
    optparse::make_option(
      c("--mpa-reports"),
      dest = "mpa_reports",
      action = "store",
      default = NA,
      type = "character",
      help = "Path to directory containing MPA-style reports generated by Kraken2."
    ),
    optparse::make_option(
      c("--organism"),
      dest = "organism",
      action = "store",
      default = NA,
      type = "character",
      help = "Species of the organism being analysed."
    ),
    optparse::make_option(
      c("-r", "--reference"),
      dest = "refdb",
      action = "store",
      default = NA,
      type = "character",
      help = "Path to an 'inspect.txt' file in a Kraken2 reference database."
    ),
    optparse::make_option(
      c("-m", "--metadata"),
      dest = "metadata",
      action = "store",
      default = NA,
      type = "character",
      help = "Path to metadata file [optional]."
    ),
    optparse::make_option(
      c("--sample-col"),
      dest = "sample_col",
      action = "store",
      default = NA,
      type = "character",
      help = "Sample column in metadata table [if metadata file was provided]."
    ),
    optparse::make_option(
      c("-c", "--columns"),
      dest = "columns",
      action = "store",
      default = NA,
      type = "character",
      help = "Comma-separated column names [if metadata file was provided]."
    ),
    optparse::make_option(
      c("-p", "--prefix"),
      dest = "prefix",
      action = "store",
      default = "",
      type = "character",
      help = "Prefix to be added to output files."
    ),
    optparse::make_option(
      c("-o", "--outdir"),
      dest = "outdir",
      action = "store",
      default = NA,
      type = "character",
      help = "Path to output directory."
    ),
    optparse::make_option(
      c("--verbosity"),
      dest = "verbosity",
      action = "store",
      default = logger::log_threshold(logger::INFO),
      help = "Verbosity level (one of 'trace'/'t', 'debug'/'d', 'info'/'i', 'success'/'s', 'warn'/'w', 'error'/'e', 'fatal'/'f' or 'off'/'o')."
    ),
    optparse::make_option(
      c("--include-eukaryotes"),
      dest = "inc_eukaryotes",
      action = "store_true",
      default = FALSE,
      type = "logical",
      help = "Include eukaryotes in the final results table and plots."
    ),
    optparse::make_option(
      c("--include-sample-names"),
      dest = "inc_sample_names",
      action = "store_true",
      default = FALSE,
      type = "logical",
      help = "Include sample names in the plots."
    ),
    optparse::make_option(
      c("-d", "--domain"),
      dest = "domain",
      action = "store",
      default = NA,
      type = "character",
      help = "Comma-separated list with domains of interest (e.g. Viruses,Bacteria)."
    ),
    optparse::make_option(
      c("-s", "--samples-to-remove"),
      dest = "samples_to_remove",
      action = "store",
      default = NA,
      type = "character",
      help = "Samples to remove from SPARKI analysis."
    ),
    optparse::make_option(
      c("--version"),
      action = "store_true",
      default = FALSE,
      type = "logical",
      help = "Print version information and exit."
    )
  )

  # Collect the command line arguments
  from_cli_args <- commandArgs(trailingOnly = TRUE)

  # Create the parser
  parser <- optparse::OptionParser(
    option_list = option_list,
    add_help_option = TRUE,
    description = CLI_DESCRIPTION,
    prog = CLI_PROGRAM_NAME
  )

  # Parse the CLI arguments into R objects
  arguments <- optparse::parse_args(parser, args = from_cli_args)

  # Check for version flag first
  if (arguments$version) {
    version <- utils::packageVersion("SPARKI")
    cat(sprintf("%s version %s\n", CLI_PROGRAM_NAME, version))
    return(invisible())
  }

  verbosity <- arguments$verbosity
  if (verbosity %in% c("trace", "t")) logger::log_threshold(logger::TRACE)
  else if (verbosity %in% c("debug", "d")) logger::log_threshold(logger::DEBUG)
  else if (verbosity %in% c("info", "i")) logger::log_threshold(logger::INFO)
  else if (verbosity %in% c("success", "s")) logger::log_threshold(logger::SUCCESS)
  else if (verbosity %in% c("warn", "w")) logger::log_threshold(logger::WARN)
  else if (verbosity %in% c("error", "e")) logger::log_threshold(logger::ERROR)
  else if (verbosity %in% c("fatal", "f")) logger::log_threshold(logger::FATAL)
  else if (verbosity %in% c("off", "o")) logger::log_threshold(logger::OFF)
  else {
    logger::log_warn(CLI_VERBOSITY_NOT_VALID)
    logger::log_threshold(logger::INFO)
  }

  # Check all required arguments have been provided.
  required_arguments <- c(
    arguments$std_reports, arguments$mpa_reports, arguments$organism,
    arguments$refdb, arguments$outdir, arguments$domain
  )
  names(required_arguments) <- c(
    "Standard reports directory", "MPA-style reports directory", "Organism",
    "Kraken2 reference database", "Output directory", "Domain"
  )
  for (argument in required_arguments) {
    if (is.na(argument)) {
      arg_name <- names(required_arguments)[required_arguments == argument]
      error_message <- paste0(CLI_ARGUMENT_NOT_PROVIDED, glue::double_quote(arg_name))
      logger::log_fatal(error_message)
      stop(error_message)
    }
  }

  logger::log_debug(CLI_ARGUMENTS)
  logger::log_debug(paste0(CLI_ARGUMENT_STD_REPORTS, arguments$std_reports))
  logger::log_debug(paste0(CLI_ARGUMENT_MPA_REPORTS, arguments$mpa_reports))
  logger::log_debug(paste0(CLI_ARGUMENT_ORGANISM, arguments$organism))
  logger::log_debug(paste0(CLI_ARGUMENT_REFERENCE, arguments$refdb))
  logger::log_debug(paste0(CLI_ARGUMENT_METADATA, arguments$metadata))
  logger::log_debug(paste0(CLI_ARGUMENT_SAMPLE_COL, arguments$sample_col))
  logger::log_debug(paste0(CLI_ARGUMENT_COLUMNS, arguments$columns))
  logger::log_debug(paste0(CLI_ARGUMENT_OUTDIR, arguments$outdir))
  logger::log_debug(paste0(CLI_ARGUMENT_PREFIX, arguments$prefix))
  logger::log_debug(paste0(CLI_ARGUMENT_VERBOSE, arguments$verbosity))
  logger::log_debug(paste0(CLI_ARGUMENT_INC_EUKARYOTES, arguments$inc_eukaryotes))
  logger::log_debug(paste0(CLI_ARGUMENT_INC_SAMPLE_NAMES, arguments$inc_sample_names))
  logger::log_debug(paste0(CLI_ARGUMENT_DOMAIN, arguments$domain))
  logger::log_debug(paste0(CLI_ARGUMENT_SAMPLES_TO_REMOVE, arguments$samples_to_remove))

  # Carry out SPARKI analysis.
  run_analysis(
    std_reports_path = arguments$std_reports,
    mpa_reports_path = arguments$mpa_reports,
    organism = arguments$organism,
    reference_path = arguments$refdb,
    metadata_path = arguments$metadata,
    metadata_sample_col = arguments$sample_col,
    metadata_columns = arguments$columns,
    outdir_path = arguments$outdir,
    prefix = arguments$prefix,
    include_eukaryotes = arguments$inc_eukaryotes,
    include_sample_names = arguments$inc_sample_names,
    domain = arguments$domain,
    samples_to_remove = arguments$samples_to_remove
  )
}
