######################
## HELPER CONSTANTS ##
#####################################################################

#### Reference database ####
COLNAME_REF_DB_PCT_FRAG_CLADE <- "pct_fragments_clade"
COLNAME_REF_DB_MINIMISERS_CLADE <- "n_minimisers_clade"
COLNAME_REF_DB_MINIMISERS_TAXON <- "n_minimisers_taxon"
COLNAME_REF_DB_RANK <- "rank"
COLNAME_REF_DB_NCBI_ID <- "ncbi_id"
COLNAME_REF_DB_TAXON <- "taxon"

#### Standard report ####
COLNAME_STD_SAMPLE <- "sample"
COLNAME_STD_PCT_FRAG_CLADE <- "pct_fragments_clade"
COLNAME_STD_N_FRAG_CLADE <- "n_fragments_clade"
COLNAME_STD_N_FRAG_TAXON <- "n_fragments_taxon"
COLNAME_STD_MINIMISERS <- "n_minimisers"
COLNAME_STD_UNIQ_MINIMISERS <- "n_distinct_minimisers"
COLNAME_STD_RANK <- "rank"
COLNAME_STD_NCBI_ID <- "ncbi_id"
COLNAME_STD_TAXON <- "taxon"
COLNAME_STD_HIERARCHY <- "info_from_mpa_report"
COLNAME_STD_TOTAL_READS <- "n_total_reads_in_sample"
COLNAME_STD_DOMAIN <- "domain"
COLNAME_STD_DB_MINIMISERS_CLADE <- "db_n_minimisers_clade"
COLNAME_STD_DB_MINIMISERS_TAXON <- "db_n_minimisers_taxon"
COLNAME_STD_RATIO_CLADE <- "ratio_clade"
COLNAME_STD_RATIO_TAXON <- "ratio_taxon"
COLNAME_STD_P_CLADE_IN_DB <- "p_clade_in_db"
COLNAME_STD_PVALUE <- "pvalue"
COLNAME_STD_PADJ <- "padj"
COLNAME_STD_SIGNIF <- "significance"

#### MPA-style report #### 
COLNAME_MPA_SAMPLE <- "sample"
COLNAME_MPA_N_FRAG_CLADE <- "n_fragments_clade"
COLNAME_MPA_TAXON <- "taxon_hierarchy"
COLNAME_MPA_RANK <- "rank"
COLNAME_MPA_NCBI_ID <- "ncbi_id"
COLNAME_MPA_TOTAL_READS <- "n_total_reads_in_sample"
COLNAME_MPA_DB_MINIMISERS_CLADE <- "db_n_minimisers_clade"
COLNAME_MPA_DB_MINIMISERS_TAXON <- "db_n_minimisers_taxon"
COLNAME_MPA_RATIO_CLADE <- "ratio_clade"

#### Auxiliary dataframes ####

# Number of domain reads per sample.
COLNAME_DOMAIN_READS_SAMPLE <- "sample"
COLNAME_DOMAIN_READS_SCOPE <- "domains_considered"
COLNAME_DOMAIN_READS_N_READS <- "n_clade_reads"

# Number of classified/unclassified reads per sample.
COLNAME_CLASSIF_SUMMARY_SAMPLE <- "sample"
COLNAME_CLASSIF_SUMMARY_READ_TYPE <- "type"
COLNAME_CLASSIF_SUMMARY_N_READS <- "n_reads"

#### Rank names ####
NAME_RANK_UNCLASS <- "unclassified"
NAME_RANK_ROOT <- "root"
NAME_RANK_SUBROOT_1 <- "subroot_1"
NAME_RANK_SUBROOT_2 <- "subroot_2"
NAME_RANK_SUBROOT_3 <- "subroot_3"
NAME_RANK_DOMAIN <- "domain"
NAME_RANK_SUBDOMAIN_1 <- "subdomain_1"
NAME_RANK_SUBDOMAIN_2 <- "subdomain_2"
NAME_RANK_SUBDOMAIN_3 <- "subdomain_3"
NAME_RANK_SUBDOMAIN_4 <- "subdomain_4"
NAME_RANK_SUBDOMAIN_5 <- "subdomain_5"
NAME_RANK_KINGDOM <- "kingdom"
NAME_RANK_SUBKINGDOM_1 <- "subkingdom_1"
NAME_RANK_SUBKINGDOM_2 <- "subkingdom_2"
NAME_RANK_SUBKINGDOM_3 <- "subkingdom_3"
NAME_RANK_PHYLUM <- "phylum"
NAME_RANK_SUBPHYLUM_1 <- "subphylum_1"
NAME_RANK_SUBPHYLUM_2 <- "subphylum_2"
NAME_RANK_SUBPHYLUM_3 <- "subphylum_3"
NAME_RANK_SUBPHYLUM_4 <- "subphylum_4"
NAME_RANK_SUBPHYLUM_5 <- "subphylum_5"
NAME_RANK_SUBPHYLUM_6 <- "subphylum_6"
NAME_RANK_SUBPHYLUM_7 <- "subphylum_7"
NAME_RANK_SUBPHYLUM_8 <- "subphylum_8"
NAME_RANK_SUBPHYLUM_9 <- "subphylum_9"
NAME_RANK_CLASS <- "class"
NAME_RANK_SUBCLASS_1 <- "subclass_1"
NAME_RANK_SUBCLASS_2 <- "subclass_2"
NAME_RANK_SUBCLASS_3 <- "subclass_3"
NAME_RANK_SUBCLASS_4 <- "subclass_4"
NAME_RANK_SUBCLASS_5 <- "subclass_5"
NAME_RANK_SUBCLASS_6 <- "subclass_6"
NAME_RANK_ORDER <- "order"
NAME_RANK_SUBORDER_1 <- "suborder_1"
NAME_RANK_SUBORDER_2 <- "suborder_2"
NAME_RANK_SUBORDER_3 <- "suborder_3"
NAME_RANK_SUBORDER_4 <- "suborder_4"
NAME_RANK_FAMILY <- "family"
NAME_RANK_SUBFAMILY_1 <- "subfamily_1"
NAME_RANK_SUBFAMILY_2 <- "subfamily_2"
NAME_RANK_SUBFAMILY_3 <- "subfamily_3"
NAME_RANK_SUBFAMILY_4 <- "subfamily_4"
NAME_RANK_SUBFAMILY_5 <- "subfamily_5"
NAME_RANK_SUBFAMILY_6 <- "subfamily_6"
NAME_RANK_SUBFAMILY_7 <- "subfamily_7"
NAME_RANK_GENUS <- "genus"
NAME_RANK_SUBGENUS_1 <- "subgenus_1"
NAME_RANK_SUBGENUS_2 <- "subgenus_2"
NAME_RANK_SUBGENUS_3 <- "subgenus_3"
NAME_RANK_SPECIES <- "species"
NAME_RANK_SUBSPECIES_1 <- "subspecies_1"
NAME_RANK_SUBSPECIES_2 <- "subspecies_2"
NAME_RANK_SUBSPECIES_3 <- "subspecies_3"
NAME_RANK_SUBSPECIES_4 <- "subspecies_4"