#' Prepare report for plotMinimisers_dotplot()
#'
#' @param report A report generated by mergeReports() and with statistical
#'  assessment results generated by assessStatistics().
#' @param domain_of_interest The domain that should be included in the plot
#'  generated by plotMinimisers_dotplot().
#'
#' @return An updated version of the report provided as input, suitable for
#'  use by the function plotMinimisers_dotplot().
#'
prepare_for_plotMinimisers <- function(report, domain_of_interest) {
  if(!(COLNAME_STD_PADJ %in% colnames(report))) {
    logger::log_fatal(PREPARE_PLOT_MINIMISERS_PADJ_NOT_FOUND)
    stop(PREPARE_PLOT_MINIMISERS_PADJ_NOT_FOUND)
  }

  subset <- report |>
    # Select relevant rows.
    dplyr::filter(!!as.name(COLNAME_MPA_DOMAIN) == domain_of_interest) |>
    # Select relevant columns.
    dplyr::select(
      !!COLNAME_STD_SAMPLE,
      !!COLNAME_STD_TAXON,
      !!COLNAME_STD_RANK,
      !!COLNAME_MPA_DOMAIN,
      !!COLNAME_STD_N_FRAG_CLADE,
      !!COLNAME_STD_RATIO_CLADE,
      !!COLNAME_STD_PADJ,
      !!COLNAME_STD_SIGNIF
    ) |>
    #  Create column with log-transformed number of clade-level fragments.
    dplyr::mutate(
      !!COLNAME_STD_LOG_N_FRAG_CLADE := log10(!!as.name(COLNAME_STD_N_FRAG_CLADE))
    ) |>
    # Reorder columns.
    dplyr::relocate(
      !!COLNAME_STD_LOG_N_FRAG_CLADE,
      .after = !!COLNAME_STD_N_FRAG_CLADE
    ) |>
    #  Replace values in column.
    dplyr::mutate(!!COLNAME_STD_RANK := dplyr::case_when(
      !!as.name(COLNAME_STD_RANK) == "F" ~ "Family",
      !!as.name(COLNAME_STD_RANK) == "G" ~ "Genus",
      !!as.name(COLNAME_STD_RANK) == "S" ~ "Species"
    ))

  logger::log_debug(PREPARE_PLOT_MINIMISERS_SUCCESS)

  return(subset)
}

#' Plot proportion of minimisers and significance per sample
#'
#' @param report A report generated by mergeReports() and processed by
#'  assessStatistics().
#' @param domain Domain of interest.
#' @param fig_width Width for output PDF file.
#' @param fig_height Height for output PDF file.
#' @param return_plot Whether plot should be returned.
#' @param outdir Output directory where the plot should be saved.
#' @param prefix Prefix to be added to output file name.
#'
#' @return If return_plot = TRUE, returns a dot plot with the minimiser
#'  proportions and adjusted p-values.
#'
#' @export
#'
plotMinimisers_dotplot <- function(
    report,
    domain,
    fig_width,
    fig_height,
    return_plot,
    outdir,
    prefix) {
  # Assign NA to outdir in case it has not been provided by the user.
  if (missing(outdir)) outdir <- NA

  df <- prepare_for_plotMinimisers(report, domain)

  # If there are both significant and non-significant results...
  if ("Significant" %in% df[[COLNAME_STD_SIGNIF]] && "Non-significant" %in% df[[COLNAME_STD_SIGNIF]]) {
    ggplot_colours <- c("snow3", "black")
    ggplot_labels <- c("Non-significant", expression("Adjusted p-value" <= "0.05"))

  # If there are only significant results...
  } else if ("Significant" %in% df[[COLNAME_STD_SIGNIF]] && !("Non-significant" %in% df[[COLNAME_STD_SIGNIF]])) {
    ggplot_colours <- "black"
    ggplot_labels <- expression("Adjusted p-value" <= "0.05")

  # If there are only non-significant results...
  } else if (!("Significant" %in% df[[COLNAME_STD_SIGNIF]]) && "Non-significant" %in% df[[COLNAME_STD_SIGNIF]]) {
    ggplot_colours <- "snow3"
    ggplot_labels <- "Non-significant"

  # Else...
  } else {
    logger::log_fatal(PLOT_MINIMISERS_SIGNIF_NOT_FOUND)
    stop(PLOT_MINIMISERS_SIGNIF_NOT_FOUND)
  }

  # Get total number of samples.
  n_all_samples <- report[[COLNAME_STD_SAMPLE]] |> unique() |> length()
  # Get number of samples with results available.
  n_subset_samples <- df[[COLNAME_STD_SAMPLE]] |> unique() |> length()

  plot <- ggplot2::ggplot(
    df,
    ggplot2::aes(
      x = get(COLNAME_STD_SAMPLE),
      y = get(COLNAME_STD_TAXON),
      fill = get(COLNAME_STD_RATIO_CLADE),
      color = get(COLNAME_STD_SIGNIF),
      size = get(COLNAME_STD_LOG_N_FRAG_CLADE)
    )
  ) +
    ggplot2::geom_point(shape = 21, stroke = 1.25) +
    ggplot2::facet_grid(
      rows = ggplot2::vars(get(COLNAME_STD_RANK)),
      scales = "free_y",
      space = "free_y"
    ) +
    ggplot2::theme_bw() +
    ggplot2::theme(
      axis.text.x = ggplot2::element_text(size = 10, angle = 90, vjust = 0.5, hjust = 1),
      axis.text.y = ggplot2::element_text(size = 12),
      legend.text = ggplot2::element_text(size = 15, hjust = 0),
      legend.title = ggplot2::element_text(size = 15),
      axis.title = ggplot2::element_text(size = 15),
      plot.title = ggplot2::element_text(size = 16.5, face = "bold", hjust = 0.5),
      strip.text.y = ggplot2::element_text(size = 15, face = "bold")
    ) +
    ggplot2::scale_fill_gradientn(
      colors = grDevices::colorRampPalette(RColorBrewer::brewer.pal(9, "Reds"))(100),
      name = "Proportion of clade-level minimisers\nfound in the sample",
      limits = c(0, 1)
    ) +
    ggplot2::scale_color_manual(
      values = ggplot_colours,
      name = "Significance",
      labels = ggplot_labels
    ) +
    ggplot2::scale_size_continuous(name = expression("log"[10] ~ "(clade-level reads)")) +
    ggplot2::xlab("Sample") +
    ggplot2::ylab("Taxon") +
    ggplot2::ggtitle(
      paste0(
        "Showing ", n_subset_samples, " samples (out of ", n_all_samples,
        ") with results available for domain: ", domain
      )
    )

  handlePlot(
    plot = plot,
    prefix = prefix,
    return_plot = return_plot,
    filename = paste0(domain, "_propMinimisers_and_pvalues.pdf"),
    outdir = outdir,
    fig_width = fig_width,
    fig_height = fig_height
  )

  logger::log_info(PLOT_MINIMISERS_SUCCESS)
}
