#' Plot a summary of statistical significance results
#'
#' @param report A report generated by mergeReports() and processed
#'  with assessStatistics().
#' @param return_plot Whether plot should be returned.
#' @param outdir Output directory where the plot should be saved.
#' @param prefix Prefix to be added to output file name.
#'
#' @return If return_plot = TRUE, returns the plot.
#'
#' @export
#'
plotSignificanceSummary <- function(report, return_plot, outdir, prefix) {
  summary <- getSignificanceSummary(report)

  # If there are both significant and non-significant results...
  if ("Significant" %in% summary[[COLNAME_SIGNIF_SUMMARY_SIGNIF]] && "Non-significant" %in% summary[[COLNAME_SIGNIF_SUMMARY_SIGNIF]]) {
    ggplot_colours <- c("snow3", "black")
    ggplot_labels <- c("Non-significant", expression("Adjusted p-value" <= "0.05"))

  # If there are only significant results...
  } else if ("Significant" %in% summary[[COLNAME_SIGNIF_SUMMARY_SIGNIF]] && !("Non-significant" %in% summary[[COLNAME_SIGNIF_SUMMARY_SIGNIF]])) {
    ggplot_colours <- "black"
    ggplot_labels <- expression("Adjusted p-value" <= "0.05")

  # If there are only non-significant results...
  } else if (!("Significant" %in% summary[[COLNAME_SIGNIF_SUMMARY_SIGNIF]]) && "Non-significant" %in% summary[[COLNAME_SIGNIF_SUMMARY_SIGNIF]]) {
    ggplot_colours <- "snow3"
    ggplot_labels <- "Non-significant"

  # Else...
  } else {
    logger::log_fatal(PLOT_SIGNIFICANCE_SIGNIF_NOT_FOUND)
    stop(PLOT_SIGNIFICANCE_SIGNIF_NOT_FOUND)
  }

  plot <- ggplot2::ggplot(
    summary,
    ggplot2::aes(
      x = get(COLNAME_SIGNIF_SUMMARY_SAMPLE),
      y = get(COLNAME_SIGNIF_SUMMARY_N_TAXA),
      fill = get(COLNAME_SIGNIF_SUMMARY_SIGNIF)
    )
  ) +
    ggplot2::geom_bar(position = "fill", stat = "identity") +
    ggplot2::facet_wrap(
      ~ get(COLNAME_SIGNIF_SUMMARY_RANK),
      ncol = 1
    ) +
    ggplot2::theme_classic() +
    ggplot2::theme(
      #  x-axis
      axis.text.x = ggplot2::element_blank(),
      axis.title.x = ggplot2::element_text(size = 16),
      axis.ticks.x = ggplot2::element_blank(),
      # y-axis
      axis.text.y = ggplot2::element_text(size = 15),
      axis.title.y = ggplot2::element_text(size = 16),
      # legend
      legend.text = ggplot2::element_text(size = 15),
      legend.title = ggplot2::element_text(size = 16),
      legend.justification = "top"
    ) +
    ggplot2::xlab("\nSample\n") +
    ggplot2::ylab("Proportion of taxa\n") +
    ggplot2::scale_fill_manual(
      values = ggplot_colours,
      name = "Significance",
      labels = ggplot_labels
    )

  #  Decide what to do with plot based on user-defined options.
  handlePlot(
    plot = plot, prefix = prefix, return_plot = return_plot,
    filename = "SignificanceSummary.pdf", outdir = outdir, fig_width = 10,
    fig_height = 5
  )

  logger::log_info(PLOT_SIGNIFICANCE_SUCCESS)
}

#' Prepare report for plotSignficanceSummary()
#'
#' @param report A report generated by mergeReports() and processed by
#'  assessStatistics().
#'
#' @return An updated version of the report provided as input, suitable for
#'  use by the function plotSignficanceSummary().
#'
getSignificanceSummary <- function(report) {
  if(!(COLNAME_STD_SIGNIF %in% colnames(report))) {
    logger::log_fatal(GET_SIGNIFICANCE_SIGNIF_NOT_FOUND)
    stop(GET_SIGNIFICANCE_SIGNIF_NOT_FOUND)
  }

  summary <- report |>
    # Select relevant columns.
    dplyr::select(
      !!COLNAME_STD_SAMPLE,
      !!COLNAME_STD_RANK,
      !!COLNAME_STD_TAXON,
      !!COLNAME_STD_SIGNIF
    ) |>
    #  Create grouping based on sample ID, rank and statistical significance.
    dplyr::group_by(
      !!as.name(COLNAME_STD_SAMPLE),
      !!as.name(COLNAME_STD_RANK),
      !!as.name(COLNAME_STD_SIGNIF)
    ) |>
    #  Count number of taxa per group.
    dplyr::summarise(
      !!COLNAME_SIGNIF_SUMMARY_N_TAXA := length(!!as.name(COLNAME_STD_TAXON)),
      .groups = "keep"
    ) |>
    # Rename columns.
    dplyr::rename(
      !!COLNAME_SIGNIF_SUMMARY_SAMPLE := !!COLNAME_STD_SAMPLE,
      !!COLNAME_SIGNIF_SUMMARY_RANK := !!COLNAME_STD_RANK,
      !!COLNAME_SIGNIF_SUMMARY_SIGNIF := !!COLNAME_STD_SIGNIF
    ) |>
    #  Replace values in column.
    dplyr::mutate(!!COLNAME_SIGNIF_SUMMARY_RANK := dplyr::case_when(
      !!as.name(COLNAME_SIGNIF_SUMMARY_RANK) == "F" ~ "Family",
      !!as.name(COLNAME_SIGNIF_SUMMARY_RANK) == "G" ~ "Genus",
      !!as.name(COLNAME_SIGNIF_SUMMARY_RANK) == "S" ~ "Species"
    ))

  logger::log_debug(GET_SIGNIFICANCE_SUCCESS)

  return(summary)
}
