#' Define rank for a given taxon hierarchy from an MPA-style report
#'
#' @param taxon A taxon hierarchy from an MPA-style report.
#'
#' @return The rank corresponding to the given taxon hierarchy.
#'
addRank <- function(taxon) {
  # Define rank prefixes and corresponding letters.
  rank_prefixes <- c("d__", "k__", "p__", "c__", "o__", "f__", "g__", "s__")
  rank_letters <- c("D", "K", "P", "C", "O", "F", "G", "S")

  # Create a single regex pattern.
  pattern <- paste0("(", paste(rank_prefixes, collapse = "|"), ")")

  # Extract all rank prefixes from each taxon string.
  all_matches <- stringr::str_extract_all(taxon, pattern)

  # Find the last (most specific) rank for each taxon.
  last_ranks <- sapply(all_matches, function(x) utils::tail(x, 1))

  # Map rank prefixes to letters.
  rank <- rank_letters[match(last_ranks, rank_prefixes)]

  return(rank)
}

#' Calculate sample sizes
#'
#' @param report A report generated by mergeReports() or loaded with load_STDreports().
#'
#' @return An updated version of the report provided as input, with a new column containing
#'  sample sizes
#'
#' @export
#'
addSampleSize <- function(report) {
  subset <- report |>
    #  Select columns of interest.
    dplyr::select(!!COLNAME_STD_SAMPLE, !!COLNAME_STD_TAXON, !!COLNAME_STD_N_FRAG_CLADE) |>
    # Select rows of interest.
    dplyr::filter(!!as.name(COLNAME_STD_TAXON) %in% c("unclassified", "root")) |>
    #  Reformat dataframe into a more convenient shape.
    tidyr::pivot_wider(
      names_from = !!COLNAME_STD_TAXON,
      values_from = !!COLNAME_STD_N_FRAG_CLADE
    ) |>
    #  Rename columns.
    dplyr::rename(
      Unclassified = unclassified,
      Classified = root
    ) |>
    #  Create column with sample sizes (i.e. sum of unclasified and classified reads).
    dplyr::mutate(!!COLNAME_STD_SAMPLE_SIZE := rowSums(dplyr::across((where(is.numeric))))) |>
    #  Select final columns.
    dplyr::select(!!COLNAME_STD_SAMPLE, !!COLNAME_STD_SAMPLE_SIZE)

  #  Add sample sizes to report.
  report <- dplyr::left_join(report, subset, by = dplyr::join_by(!!COLNAME_STD_SAMPLE)) |>
    #  Reorder columns.
    dplyr::relocate(!!COLNAME_STD_SAMPLE_SIZE, .after = !!COLNAME_STD_SAMPLE)

  logger::log_info(ADD_INFO_SAMPLE_SIZE_SUCCESS)

  return(report)
}

#' Add minimiser data to the report
#'
#' @param report A report generated by mergeReports() or loaded with load_STDreports().
#' @param ref_db A Kraken2 reference database 'inspect.txt' file loaded with loadReference().
#'
#' @return An updated version of the report provided as input, with new columns containing
#'  the number of taxon-level and clade-level minimisers from the database available for each
#'  taxon.
#'
#' @export
#'
addMinimiserData <- function(report, ref_db) {
  # Select relevant columns.
  ref_db <- ref_db |>
    dplyr::select(
      !!COLNAME_REF_DB_NCBI_ID,
      !!COLNAME_REF_DB_MINIMISERS_TAXON,
      !!COLNAME_REF_DB_MINIMISERS_CLADE
    )

  report <- report |>
    #  Add DB info to the report.
    dplyr::left_join(ref_db, by = dplyr::join_by(!!COLNAME_STD_NCBI_ID)) |>
    # Rename columns.
    dplyr::rename(
      !!COLNAME_STD_DB_MINIMISERS_CLADE := !!COLNAME_REF_DB_MINIMISERS_CLADE,
      !!COLNAME_STD_DB_MINIMISERS_TAXON := !!COLNAME_REF_DB_MINIMISERS_TAXON
    )

  logger::log_info(ADD_INFO_MINIMISERS_SUCCESS)

  return(report)
}

#' Count the number of taxa per taxonomic rank in each sample
#'
#' @param report A report generated by mergeReports() or loaded with load_STDreports().
#'
#' @return An updated version of the report provided as input, with a new column containing
#'  the number of taxa present per taxonomic rank in each sample.
#'
#' @export
#'
add_nTaxaInRank <- function(report) {
  n_taxa_in_rank <- report |>
    #  Create column with sample+rank combinations.
    dplyr::mutate(
      temp = paste(!!as.name(COLNAME_STD_SAMPLE), !!as.name(COLNAME_STD_RANK), sep = "_")
    ) |>
    #  Count sample+rank occurrences (this will tell how many taxa are present in each rank
    #  for each sample).
    dplyr::count(temp)

  report <- report |>
    #  Create temporary column with sample+rank combinations.
    dplyr::mutate(
      temp = paste(!!as.name(COLNAME_STD_SAMPLE), !!as.name(COLNAME_STD_RANK), sep = "_")
    ) |>
    #  Merge dataframes.
    dplyr::left_join(n_taxa_in_rank, by = dplyr::join_by(temp)) |>
    #  Remove the temporary column.
    dplyr::select(!temp) |>
    #  Rename column.
    dplyr::rename(!!COLNAME_STD_N_TAXA_RANK := n) |>
    # Relocate column.
    dplyr::relocate(!!COLNAME_STD_N_TAXA_RANK, .after = !!COLNAME_STD_RANK)

  report[[COLNAME_STD_N_TAXA_RANK]] <- as.numeric(report[[COLNAME_STD_N_TAXA_RANK]])

  logger::log_info(ADD_INFO_N_TAXA_SUCCESS)

  return(report)
}


#' Add metadata columns to report
#'
#' This function takes as input a report (loaded with load_STDreports() or load_MPAreports(), or generated by
#' mergeReports()) and a metadata table (loaded with loadMetadata()) and adds specified columns from the latter
#' to the former.
#'
#' @param report A report generated by load_STDreports(), load_MPAreports() or mergeReports().
#' @param metadata A metadata table loaded with loadMetadata().
#' @param metadata_sample_col The name of the column in the metadata table that contains sample IDs (these sample
#'  IDs must match the sample IDs present in the report).
#' @param metadata_columns The names of the columns in the metadata table that should be added to the report.
#'
#' @return An updated version of the report, containing the metadata columns specified.
#'
#' @export
#'
addMetadata <- function(report, metadata, metadata_sample_col, metadata_columns) {
  #  Check report format.
  report_colname_sample <- ifelse(is_mpa(report), COLNAME_MPA_SAMPLE, COLNAME_STD_SAMPLE)

  #  Process metadata dataframe (tibble).
  metadata <- metadata |>
    # Select metadata columns that will be added to the report.
    dplyr::select(dplyr::all_of(metadata_sample_col), dplyr::all_of(metadata_columns)) |>
    # Rename column with sample IDs to keep its name consistent
    #  with the report.
    dplyr::rename(!!report_colname_sample := dplyr::all_of(metadata_sample_col))

  #  Replace spaces (if any) with underscores.
  colnames(metadata) <- gsub(" ", "_", colnames(metadata))
  metadata_columns <- gsub(" ", "_", metadata_columns)

  #  Add metadata columns to the report.
  report <- dplyr::left_join(
    report, metadata,
    by = dplyr::join_by(!!report_colname_sample)
  ) |>
    # Get names of columns that contain results (and not sample names / metadata) and
    # reorder the columns so that the metadata stays between the sample IDs and the
    # Kraken2 results.
    dplyr::relocate(dplyr::all_of(metadata_columns), .after = !!report_colname_sample)

  logger::log_info(ADD_INFO_METADATA_SUCCESS)

  return(report)
}
