#' Calculate the proportion of minimisers of each taxon found in each sample
#'
#' @param report A report generated by mergeReports() or loaded with load_STDreports().
#'  Note that addMinimiserData() must be run before running assessMinimiserRatio().
#'
#' @return An updated version of the report provided, containing new columns with the
#'  proportions of taxon-level and clade-level minimisers for each taxon in each sample.
#'
assessMinimiserRatio <- function(report) {
  report[, COLNAME_STD_RATIO_TAXON] <- (report[, COLNAME_STD_UNIQ_MINIMISERS] / report[, COLNAME_STD_DB_MINIMISERS_TAXON])
  report[, COLNAME_STD_RATIO_CLADE] <- (report[, COLNAME_STD_UNIQ_MINIMISERS] / report[, COLNAME_STD_DB_MINIMISERS_CLADE])

  logger::log_success("Minimiser ratio successfully calculated and added to the report.")

  return(report)
}

#' Calculate the parameters of a binomial distribution
#'
#' @param db_n_minimisers_taxon The total number of clade-level minimisers available for a given taxon in
#'  the Kraken2 reference database.
#' @param sample_size The total number of reads analysed by Kraken2 for each sample (or sample size).
#' @param ref_db The Kraken2 reference database 'inspect.txt' file loaded with loadReference().
#'
get_binomial_parameters <- function(db_n_minimisers_taxon, sample_size, ref_db) {

  # Get proportion of clade-level minimisers of a given taxon in the reference database (DB).
  # This is the same as the probability of getting this taxon from the database (probability of success).
  p_success <- (db_n_minimisers_taxon / sum(ref_db[, COLNAME_REF_DB_MINIMISERS_CLADE]))
  p_success <- as.numeric(p_success)

  # Mean is the total number of reads analysed from the sample (sample size) times the probability of success (which
  # is equal to the proportion of clade-level minimisers of the taxon out of the total available in the reference DB).
  mean <- (sample_size * p_success)
  mean <- as.numeric(mean)

  # Standard deviation = sqrt(n*P*(1-p))
  sdev <- sqrt(sample_size * p_success * (1 - p_success))
  sdev <- as.numeric(sdev)

  return(list(mean, sdev))
}

#' Calculate the p-values for each taxon in each sample
#'
#' @param sample_n_uniq_minimisers_taxon The number of unique minimisers found for a given taxon in a
#'  given sample.
#' @param db_n_minimisers_taxon The total number of clade-level minimisers available for a given taxon in
#'  the Kraken2 reference database.
#' @param sample_size The total number of reads analysed by Kraken2 for each sample (or sample size).
#' @param ref_db The Kraken2 reference database 'inspect.txt' file loaded with loadReference().
#'
calculate_p_value <- function(sample_n_uniq_minimisers_taxon, db_n_minimisers_taxon, sample_size, ref_db) {

  binomial_parameters <- get_binomial_parameters(db_n_minimisers_taxon, sample_size, ref_db)

  #  Calculate p-values.
  pval <- stats::pnorm(
    q = as.numeric(sample_n_uniq_minimisers_taxon),
    mean = binomial_parameters[[1]],
    sd = binomial_parameters[[2]],
    lower.tail = FALSE
  )

  pval <- as.numeric(pval)

  return(pval)
}

#' Assess the statistical significance of the Kraken2 results
#'
#' @param report A report generated by mergeReports() and processed with addSampleSize(), addMinimiserData()
#'  and assessMinimiserRatio().
#' @param ref_db A Kraken2 reference database 'inspect.txt' file loaded with loadReference().
#'
#' @return An updated version of the report provided as input, with new columns containing statistical
#'  significance results.
#'
#' @export
#'
assessStatistics <- function(report, ref_db) {
  logger::log_info("Estimating p-values...")

  # Calculate p-values.
  report[, COLNAME_STD_PVALUE] <- calculate_p_value(
    report[[COLNAME_STD_UNIQ_MINIMISERS]],
    report[[COLNAME_STD_DB_MINIMISERS_CLADE]],
    report[[COLNAME_STD_SAMPLE_SIZE]],
    ref_db
  )

  logger::log_info("Adjusting p-values...")

  # Perform p-value correction.
  report[, COLNAME_STD_PADJ] <- sapply(seq_len(nrow(report)), function(x) {
    stats::p.adjust(
      report[[COLNAME_STD_PVALUE]][x],
      method = "BH",
      n = report[[COLNAME_STD_N_TAXA_RANK]][x]
    )
  })

  #  Add column stating whether results are significant or not based on the adjusted p-value.
  report[, COLNAME_STD_SIGNIF] <- ifelse(
    report[, COLNAME_STD_PADJ] <= 0.05,
    "Significant",
    "Non-significant"
  )

  logger::log_success("Statistical assessment successfully completed!")

  return(report)
}
